In [20]:
import torch
import pandas as pd




In [41]:
import numpy as np
df = pd.read_csv('Iris.csv')
df.Species= pd.factorize(df.Species)[0] + 1
df
labels=df.iloc[0:,-1]
features=df.iloc[:,1:-1]
features=features.astype(np.float32)
labels=labels.astype(np.float32)


# data = data[0:-1]
# print(features)
# print(labels)
# train_tensor = torch.tensor(train.values)

inputs = torch.from_numpy(features.values)
targets = torch.from_numpy(labels.values)

In [42]:
print(inputs)
print(targets)

tensor([[5.1000, 3.5000, 1.4000, 0.2000],
        [4.9000, 3.0000, 1.4000, 0.2000],
        [4.7000, 3.2000, 1.3000, 0.2000],
        [4.6000, 3.1000, 1.5000, 0.2000],
        [5.0000, 3.6000, 1.4000, 0.2000],
        [5.4000, 3.9000, 1.7000, 0.4000],
        [4.6000, 3.4000, 1.4000, 0.3000],
        [5.0000, 3.4000, 1.5000, 0.2000],
        [4.4000, 2.9000, 1.4000, 0.2000],
        [4.9000, 3.1000, 1.5000, 0.1000],
        [5.4000, 3.7000, 1.5000, 0.2000],
        [4.8000, 3.4000, 1.6000, 0.2000],
        [4.8000, 3.0000, 1.4000, 0.1000],
        [4.3000, 3.0000, 1.1000, 0.1000],
        [5.8000, 4.0000, 1.2000, 0.2000],
        [5.7000, 4.4000, 1.5000, 0.4000],
        [5.4000, 3.9000, 1.3000, 0.4000],
        [5.1000, 3.5000, 1.4000, 0.3000],
        [5.7000, 3.8000, 1.7000, 0.3000],
        [5.1000, 3.8000, 1.5000, 0.3000],
        [5.4000, 3.4000, 1.7000, 0.2000],
        [5.1000, 3.7000, 1.5000, 0.4000],
        [4.6000, 3.6000, 1.0000, 0.2000],
        [5.1000, 3.3000, 1.7000, 0

In [43]:
from torch.utils.data import DataLoader
from torch.utils.data import TensorDataset

In [44]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [49]:
import torch.nn as nn

In [50]:
model = nn.Linear(4, 1)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.2518, -0.4774, -0.4959, -0.3860]], requires_grad=True)
Parameter containing:
tensor([0.0577], requires_grad=True)


In [51]:
preds = model(inputs.float())

In [52]:
preds

tensor([[-3.6687],
        [-3.3797],
        [-3.3752],
        [-3.4015],
        [-3.6913],
        [-4.1612],
        [-3.5337],
        [-3.6454],
        [-3.2060],
        [-3.4384],
        [-3.8893],
        [-3.6446],
        [-3.3159],
        [-3.0412],
        [-3.9844],
        [-4.3762],
        [-3.9628],
        [-3.7073],
        [-4.1504],
        [-3.9001],
        [-3.8453],
        [-3.8910],
        [-3.3922],
        [-3.8378],
        [-3.7934],
        [-3.5040],
        [-3.7722],
        [-3.7435],
        [-3.6461],
        [-3.5240],
        [-3.5014],
        [-3.8233],
        [-3.9913],
        [-4.1036],
        [-3.4384],
        [-3.4011],
        [-3.7198],
        [-3.4384],
        [-3.2042],
        [-3.6706],
        [-3.6325],
        [-2.9338],
        [-3.2996],
        [-3.8971],
        [-4.1371],
        [-3.3931],
        [-3.9111],
        [-3.3996],
        [-3.8641],
        [-3.5480],
        [-6.1037],
        [-5.8920],
        [-6.

In [53]:
import torch.nn.functional as F

In [54]:
loss_fn = F.mse_loss

In [58]:
loss = loss_fn(model(inputs), targets.unsqueeze(1))

In [61]:
print(loss)

tensor(56.0529, grad_fn=<MseLossBackward0>)


In [62]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)