In [20]:
import torch
import pandas as pd




In [41]:
import numpy as np
df = pd.read_csv('Iris.csv')
df.Species= pd.factorize(df.Species)[0] + 1
df
labels=df.iloc[0:,-1]
features=df.iloc[:,1:-1]
features=features.astype(np.float32)
labels=labels.astype(np.float32)


# data = data[0:-1]
# print(features)
# print(labels)
# train_tensor = torch.tensor(train.values)

inputs = torch.from_numpy(features.values)
targets = torch.from_numpy(labels.values)

In [42]:
print(inputs)
print(targets)

tensor([[5.1000, 3.5000, 1.4000, 0.2000],
        [4.9000, 3.0000, 1.4000, 0.2000],
        [4.7000, 3.2000, 1.3000, 0.2000],
        [4.6000, 3.1000, 1.5000, 0.2000],
        [5.0000, 3.6000, 1.4000, 0.2000],
        [5.4000, 3.9000, 1.7000, 0.4000],
        [4.6000, 3.4000, 1.4000, 0.3000],
        [5.0000, 3.4000, 1.5000, 0.2000],
        [4.4000, 2.9000, 1.4000, 0.2000],
        [4.9000, 3.1000, 1.5000, 0.1000],
        [5.4000, 3.7000, 1.5000, 0.2000],
        [4.8000, 3.4000, 1.6000, 0.2000],
        [4.8000, 3.0000, 1.4000, 0.1000],
        [4.3000, 3.0000, 1.1000, 0.1000],
        [5.8000, 4.0000, 1.2000, 0.2000],
        [5.7000, 4.4000, 1.5000, 0.4000],
        [5.4000, 3.9000, 1.3000, 0.4000],
        [5.1000, 3.5000, 1.4000, 0.3000],
        [5.7000, 3.8000, 1.7000, 0.3000],
        [5.1000, 3.8000, 1.5000, 0.3000],
        [5.4000, 3.4000, 1.7000, 0.2000],
        [5.1000, 3.7000, 1.5000, 0.4000],
        [4.6000, 3.6000, 1.0000, 0.2000],
        [5.1000, 3.3000, 1.7000, 0

In [43]:
from torch.utils.data import DataLoader
from torch.utils.data import TensorDataset

In [44]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [49]:
import torch.nn as nn

In [50]:
model = nn.Linear(4, 1)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.2518, -0.4774, -0.4959, -0.3860]], requires_grad=True)
Parameter containing:
tensor([0.0577], requires_grad=True)


In [51]:
preds = model(inputs.float())

In [52]:
preds

tensor([[-3.6687],
        [-3.3797],
        [-3.3752],
        [-3.4015],
        [-3.6913],
        [-4.1612],
        [-3.5337],
        [-3.6454],
        [-3.2060],
        [-3.4384],
        [-3.8893],
        [-3.6446],
        [-3.3159],
        [-3.0412],
        [-3.9844],
        [-4.3762],
        [-3.9628],
        [-3.7073],
        [-4.1504],
        [-3.9001],
        [-3.8453],
        [-3.8910],
        [-3.3922],
        [-3.8378],
        [-3.7934],
        [-3.5040],
        [-3.7722],
        [-3.7435],
        [-3.6461],
        [-3.5240],
        [-3.5014],
        [-3.8233],
        [-3.9913],
        [-4.1036],
        [-3.4384],
        [-3.4011],
        [-3.7198],
        [-3.4384],
        [-3.2042],
        [-3.6706],
        [-3.6325],
        [-2.9338],
        [-3.2996],
        [-3.8971],
        [-4.1371],
        [-3.3931],
        [-3.9111],
        [-3.3996],
        [-3.8641],
        [-3.5480],
        [-6.1037],
        [-5.8920],
        [-6.

In [53]:
import torch.nn.functional as F

In [54]:
loss_fn = F.mse_loss

In [58]:
loss = loss_fn(model(inputs), targets.unsqueeze(1))

In [61]:
print(loss)

tensor(56.0529, grad_fn=<MseLossBackward0>)


In [62]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [63]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [64]:
fit(950, model, loss_fn, opt, train_dl)

/var/folders/6g/wyvpg_nj08xb0l9l4rm1mndh0000gn/T/ipykernel_27136/4082622962.py:14: UserWarning: Using a target size (torch.Size([5])) that is different to the input size (torch.Size([5, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss = loss_fn(pred, yb)


Epoch [10/950], Loss: 25.2040
Epoch [20/950], Loss: 15.4744
Epoch [30/950], Loss: 7.6385
Epoch [40/950], Loss: 3.4421
Epoch [50/950], Loss: 0.6378
Epoch [60/950], Loss: 1.6102
Epoch [70/950], Loss: 1.1185
Epoch [80/950], Loss: 0.6418
Epoch [90/950], Loss: 0.5723
Epoch [100/950], Loss: 0.9602
Epoch [110/950], Loss: 0.9297
Epoch [120/950], Loss: 0.5693
Epoch [130/950], Loss: 0.4464
Epoch [140/950], Loss: 0.8370
Epoch [150/950], Loss: 0.8601
Epoch [160/950], Loss: 0.1745
Epoch [170/950], Loss: 0.6516
Epoch [180/950], Loss: 0.5456
Epoch [190/950], Loss: 0.6822
Epoch [200/950], Loss: 0.7215
Epoch [210/950], Loss: 0.8504
Epoch [220/950], Loss: 0.4171
Epoch [230/950], Loss: 0.4463
Epoch [240/950], Loss: 0.8416
Epoch [250/950], Loss: 0.4858
Epoch [260/950], Loss: 0.6037
Epoch [270/950], Loss: 0.6269
Epoch [280/950], Loss: 0.7679
Epoch [290/950], Loss: 0.4175
Epoch [300/950], Loss: 0.6014
Epoch [310/950], Loss: 0.4274
Epoch [320/950], Loss: 0.8698
Epoch [330/950], Loss: 0.4317
Epoch [340/950], 

In [65]:
preds = model(inputs)
preds

tensor([[1.8472],
        [1.8256],
        [1.7160],
        [1.6850],
        [1.7921],
        [1.8794],
        [1.6263],
        [1.8168],
        [1.6260],
        [1.8337],
        [1.9486],
        [1.7313],
        [1.8045],
        [1.5941],
        [2.0824],
        [1.9447],
        [1.8819],
        [1.8259],
        [2.0408],
        [1.7873],
        [1.9854],
        [1.7786],
        [1.6248],
        [1.8068],
        [1.7294],
        [1.8668],
        [1.7736],
        [1.8890],
        [1.9023],
        [1.7141],
        [1.7693],
        [1.9440],
        [1.8343],
        [1.9284],
        [1.8337],
        [1.8440],
        [2.0177],
        [1.8337],
        [1.6140],
        [1.8593],
        [1.7841],
        [1.7238],
        [1.5886],
        [1.7183],
        [1.7635],
        [1.7619],
        [1.8080],
        [1.6729],
        [1.9062],
        [1.8301],
        [2.4155],
        [2.1407],
        [2.3632],
        [1.9184],
        [2.2332],
        [1