In [1]:
import torch.nn as nn
import torch
import numpy as np

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [3]:
from torch.utils.data import DataLoader
from torch.utils.data import TensorDataset

In [4]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)


In [5]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [6]:
train_dl

In [7]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 68.,  97.,  70.],
        [ 87., 134.,  58.],
        [103.,  43.,  36.],
        [ 69.,  96.,  70.],
        [ 87., 135.,  57.]])
tensor([[102., 120.],
        [119., 133.],
        [ 20.,  38.],
        [103., 119.],
        [118., 134.]])


In [8]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.0132,  0.0824, -0.4854],
        [ 0.2142, -0.3008,  0.4898]], requires_grad=True)
Parameter containing:
tensor([-0.4399, -0.2923], requires_grad=True)


In [9]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.0132,  0.0824, -0.4854],
         [ 0.2142, -0.3008,  0.4898]], requires_grad=True),
 Parameter containing:
 tensor([-0.4399, -0.2923], requires_grad=True)]

In [10]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.0132,  0.0824, -0.4854],
         [ 0.2142, -0.3008,  0.4898]], requires_grad=True),
 Parameter containing:
 tensor([-0.4399, -0.2923], requires_grad=True)]

In [11]:
# Generate predictions
preds = model(inputs)
preds

tensor([[-14.8275,  16.2507],
        [-23.0524,  24.0746],
        [-16.4014,   6.4423],
        [-13.5119,  26.7431],
        [-25.5947,  19.8944],
        [-14.8968,  16.7657],
        [-23.6202,  24.8651],
        [-16.8736,   7.1462],
        [-13.4426,  26.2281],
        [-26.0933,  20.1699],
        [-15.3953,  17.0412],
        [-23.1217,  24.5896],
        [-15.8336,   5.6517],
        [-13.0134,  26.4675],
        [-25.5255,  19.3794]], grad_fn=<AddmmBackward0>)

In [14]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.0132,  0.0824, -0.4854],
        [ 0.2142, -0.3008,  0.4898]], requires_grad=True), Parameter containing:
tensor([-0.4399, -0.2923], requires_grad=True)]


In [15]:
# Generate predictions
preds = model(inputs)
preds

tensor([[-14.8275,  16.2507],
        [-23.0524,  24.0746],
        [-16.4014,   6.4423],
        [-13.5119,  26.7431],
        [-25.5947,  19.8944],
        [-14.8968,  16.7657],
        [-23.6202,  24.8651],
        [-16.8736,   7.1462],
        [-13.4426,  26.2281],
        [-26.0933,  20.1699],
        [-15.3953,  17.0412],
        [-23.1217,  24.5896],
        [-15.8336,   5.6517],
        [-13.0134,  26.4675],
        [-25.5255,  19.3794]], grad_fn=<AddmmBackward0>)

In [16]:
# Import nn.functional
import torch.nn.functional as F

In [17]:
# Define loss function
loss_fn = F.mse_loss

In [18]:
# Define loss function
loss_fn = F.mse_loss

In [19]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(8652.7285, grad_fn=<MseLossBackward0>)


In [22]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [23]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [27]:
fit(950, model, loss_fn, opt, train_dl)

Epoch [10/950], Loss: 0.9732
Epoch [20/950], Loss: 0.9087
Epoch [30/950], Loss: 0.8397
Epoch [40/950], Loss: 1.1886
Epoch [50/950], Loss: 0.8118
Epoch [60/950], Loss: 1.1844
Epoch [70/950], Loss: 0.8126
Epoch [80/950], Loss: 0.8779
Epoch [90/950], Loss: 1.3653
Epoch [100/950], Loss: 0.7999
Epoch [110/950], Loss: 1.3205
Epoch [120/950], Loss: 1.2530
Epoch [130/950], Loss: 0.9451
Epoch [140/950], Loss: 0.6747
Epoch [150/950], Loss: 1.5001
Epoch [160/950], Loss: 0.8207
Epoch [170/950], Loss: 1.2309
Epoch [180/950], Loss: 1.1091
Epoch [190/950], Loss: 0.7278
Epoch [200/950], Loss: 0.9213
Epoch [210/950], Loss: 0.8361
Epoch [220/950], Loss: 0.9706
Epoch [230/950], Loss: 0.7713
Epoch [240/950], Loss: 1.1014
Epoch [250/950], Loss: 1.2537
Epoch [260/950], Loss: 1.0983
Epoch [270/950], Loss: 1.1228
Epoch [280/950], Loss: 1.0957
Epoch [290/950], Loss: 1.1753
Epoch [300/950], Loss: 0.7104
Epoch [310/950], Loss: 0.6814
Epoch [320/950], Loss: 1.1600
Epoch [330/950], Loss: 0.7562
Epoch [340/950], Lo

In [28]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 56.8876,  70.3347],
        [ 82.0956, 100.5564],
        [118.2084, 132.7854],
        [ 20.8367,  37.7497],
        [101.8698, 118.4809],
        [ 55.6447,  69.2587],
        [ 81.9563, 100.6547],
        [118.5096, 133.3919],
        [ 22.0796,  38.8256],
        [102.9734, 119.6551],
        [ 56.7483,  70.4330],
        [ 80.8527,  99.4804],
        [118.3477, 132.6871],
        [ 19.7331,  36.5754],
        [103.1127, 119.5568]], grad_fn=<AddmmBackward0>)

In [29]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])